// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using gozba_na_klik_backend.Model;

#nullable disable

namespace gozba_na_klik_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251125161156_v5")]
    partial class v5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomerAllergens", b =>
                {
                    b.Property<int>("AllergenId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerId")
                        .HasColumnType("text");

                    b.HasKey("AllergenId", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerAllergens");
                });

            modelBuilder.Entity("MealAllergens", b =>
                {
                    b.Property<int>("AllergenId")
                        .HasColumnType("integer");

                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.HasKey("AllergenId", "MealId");

                    b.HasIndex("MealId");

                    b.ToTable("MealAllergens");

                    b.HasData(
                        new
                        {
                            AllergenId = 1,
                            MealId = 1
                        },
                        new
                        {
                            AllergenId = 22,
                            MealId = 1
                        },
                        new
                        {
                            AllergenId = 1,
                            MealId = 2
                        },
                        new
                        {
                            AllergenId = 10,
                            MealId = 2
                        },
                        new
                        {
                            AllergenId = 9,
                            MealId = 3
                        },
                        new
                        {
                            AllergenId = 12,
                            MealId = 3
                        },
                        new
                        {
                            AllergenId = 23,
                            MealId = 4
                        },
                        new
                        {
                            AllergenId = 1,
                            MealId = 4
                        },
                        new
                        {
                            AllergenId = 1,
                            MealId = 5
                        },
                        new
                        {
                            AllergenId = 12,
                            MealId = 5
                        },
                        new
                        {
                            AllergenId = 9,
                            MealId = 6
                        },
                        new
                        {
                            AllergenId = 1,
                            MealId = 7
                        },
                        new
                        {
                            AllergenId = 22,
                            MealId = 7
                        },
                        new
                        {
                            AllergenId = 11,
                            MealId = 8
                        },
                        new
                        {
                            AllergenId = 8,
                            MealId = 8
                        },
                        new
                        {
                            AllergenId = 12,
                            MealId = 8
                        },
                        new
                        {
                            AllergenId = 1,
                            MealId = 9
                        },
                        new
                        {
                            AllergenId = 8,
                            MealId = 9
                        },
                        new
                        {
                            AllergenId = 10,
                            MealId = 9
                        },
                        new
                        {
                            AllergenId = 10,
                            MealId = 10
                        },
                        new
                        {
                            AllergenId = 13,
                            MealId = 10
                        },
                        new
                        {
                            AllergenId = 1,
                            MealId = 11
                        },
                        new
                        {
                            AllergenId = 10,
                            MealId = 11
                        },
                        new
                        {
                            AllergenId = 8,
                            MealId = 11
                        },
                        new
                        {
                            AllergenId = 9,
                            MealId = 12
                        },
                        new
                        {
                            AllergenId = 22,
                            MealId = 12
                        },
                        new
                        {
                            AllergenId = 1,
                            MealId = 13
                        },
                        new
                        {
                            AllergenId = 8,
                            MealId = 13
                        },
                        new
                        {
                            AllergenId = 10,
                            MealId = 13
                        },
                        new
                        {
                            AllergenId = 12,
                            MealId = 14
                        },
                        new
                        {
                            AllergenId = 10,
                            MealId = 15
                        },
                        new
                        {
                            AllergenId = 1,
                            MealId = 16
                        },
                        new
                        {
                            AllergenId = 12,
                            MealId = 16
                        },
                        new
                        {
                            AllergenId = 9,
                            MealId = 17
                        },
                        new
                        {
                            AllergenId = 1,
                            MealId = 18
                        },
                        new
                        {
                            AllergenId = 10,
                            MealId = 18
                        },
                        new
                        {
                            AllergenId = 5,
                            MealId = 19
                        },
                        new
                        {
                            AllergenId = 9,
                            MealId = 19
                        },
                        new
                        {
                            AllergenId = 1,
                            MealId = 20
                        },
                        new
                        {
                            AllergenId = 10,
                            MealId = 20
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "193461c3-f41b-42aa-9144-96bb85f80fef",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "40b15ed4-fb2d-4905-a923-e3a567a3f010",
                            Name = "Courier",
                            NormalizedName = "COURIER"
                        },
                        new
                        {
                            Id = "43a60b11-6cf3-4f72-a0b8-8dc7062bca6c",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = "b14a2d9f-5142-43e7-802f-3ff29d2fd0ac",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        },
                        new
                        {
                            Id = "0958f2af-39ce-41a0-96de-347c02b4e51f",
                            Name = "RestaurantOwner",
                            NormalizedName = "RESTAURANTOWNER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Belgrade",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh01",
                            Street = "Main Street",
                            StreetNumber = 12,
                            ZipCode = "11000"
                        },
                        new
                        {
                            Id = 2,
                            City = "Novi Sad",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh01",
                            Street = "Green Avenue",
                            StreetNumber = 3,
                            ZipCode = "21000"
                        },
                        new
                        {
                            Id = 3,
                            City = "Niš",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh02",
                            Street = "Sunset Blvd",
                            StreetNumber = 44,
                            ZipCode = "18000"
                        },
                        new
                        {
                            Id = 4,
                            City = "Belgrade",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh03",
                            Street = "Kralja Petra",
                            StreetNumber = 8,
                            ZipCode = "11000"
                        },
                        new
                        {
                            Id = 5,
                            City = "Belgrade",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh03",
                            Street = "Vojvode Stepe",
                            StreetNumber = 126,
                            ZipCode = "11010"
                        },
                        new
                        {
                            Id = 6,
                            City = "Zemun",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh03",
                            Street = "Cara Dušana",
                            StreetNumber = 22,
                            ZipCode = "11080"
                        },
                        new
                        {
                            Id = 7,
                            City = "Belgrade",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh04",
                            Street = "Ruzveltova",
                            StreetNumber = 33,
                            ZipCode = "11120"
                        },
                        new
                        {
                            Id = 8,
                            City = "Novi Sad",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh05",
                            Street = "Bulevar Oslobođenja",
                            StreetNumber = 99,
                            ZipCode = "21000"
                        },
                        new
                        {
                            Id = 9,
                            City = "Novi Sad",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh05",
                            Street = "Zmaj Jovina",
                            StreetNumber = 11,
                            ZipCode = "21000"
                        },
                        new
                        {
                            Id = 10,
                            City = "Belgrade",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh06",
                            Street = "Nemanjina",
                            StreetNumber = 5,
                            ZipCode = "11000"
                        },
                        new
                        {
                            Id = 11,
                            City = "Subotica",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh07",
                            Street = "Gogoljeva",
                            StreetNumber = 15,
                            ZipCode = "24000"
                        },
                        new
                        {
                            Id = 12,
                            City = "Subotica",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh07",
                            Street = "Matije Gupca",
                            StreetNumber = 2,
                            ZipCode = "24000"
                        },
                        new
                        {
                            Id = 13,
                            City = "Kragujevac",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh08",
                            Street = "Partizanska",
                            StreetNumber = 66,
                            ZipCode = "34000"
                        },
                        new
                        {
                            Id = 14,
                            City = "Čačak",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh09",
                            Street = "Vladimira Nazora",
                            StreetNumber = 7,
                            ZipCode = "32000"
                        },
                        new
                        {
                            Id = 15,
                            City = "Čačak",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh09",
                            Street = "Trg Oslobođenja",
                            StreetNumber = 1,
                            ZipCode = "32000"
                        },
                        new
                        {
                            Id = 16,
                            City = "Pančevo",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh10",
                            Street = "Industrijska",
                            StreetNumber = 10,
                            ZipCode = "26000"
                        });
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Administrator", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Allergens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "wheat"
                        },
                        new
                        {
                            Id = 2,
                            Name = "rye"
                        },
                        new
                        {
                            Id = 3,
                            Name = "barley"
                        },
                        new
                        {
                            Id = 4,
                            Name = "oats"
                        },
                        new
                        {
                            Id = 5,
                            Name = "crabs"
                        },
                        new
                        {
                            Id = 6,
                            Name = "lobsters"
                        },
                        new
                        {
                            Id = 7,
                            Name = "prawns"
                        },
                        new
                        {
                            Id = 8,
                            Name = "eggs"
                        },
                        new
                        {
                            Id = 9,
                            Name = "fish"
                        },
                        new
                        {
                            Id = 10,
                            Name = "milk"
                        },
                        new
                        {
                            Id = 11,
                            Name = "peanuts"
                        },
                        new
                        {
                            Id = 12,
                            Name = "soybean"
                        },
                        new
                        {
                            Id = 13,
                            Name = "almonds"
                        },
                        new
                        {
                            Id = 14,
                            Name = "hazelnuts"
                        },
                        new
                        {
                            Id = 15,
                            Name = "walnuts"
                        },
                        new
                        {
                            Id = 16,
                            Name = "cashews"
                        },
                        new
                        {
                            Id = 17,
                            Name = "pecan nuts"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Brazil nuts"
                        },
                        new
                        {
                            Id = 19,
                            Name = "pistachios"
                        },
                        new
                        {
                            Id = 20,
                            Name = "macadamia nuts"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Queensland nuts"
                        },
                        new
                        {
                            Id = 22,
                            Name = "celery"
                        },
                        new
                        {
                            Id = 23,
                            Name = "mustard"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Lupin"
                        },
                        new
                        {
                            Id = 25,
                            Name = "mussels"
                        },
                        new
                        {
                            Id = 26,
                            Name = "oysters"
                        },
                        new
                        {
                            Id = 27,
                            Name = "squid"
                        });
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Courier", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Couriers");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Extras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MealId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.ToTable("Extras");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MealImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Homemade peppers stuffed with minced meat and rice.",
                            MealImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1761219190/Stuffed_20Peppers_20-_20NCBA_20Beef_20Aug_20202431717_zkimq0.jpg",
                            MealName = "Stuffed Peppers",
                            Price = 6.5,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Classic pizza with ham, mushrooms, and cheese.",
                            MealImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1761219263/Pizza-Capricciosa_8_raj5pt.jpg",
                            MealName = "Capricciosa Pizza",
                            Price = 8.0,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Assorted nigiri, maki, and sashimi rolls.",
                            MealImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1761219415/omatsuri-2_c0esac.jpg",
                            MealName = "Sushi Mix",
                            Price = 12.5,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Smoked pork ribs with homemade BBQ sauce.",
                            MealImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1761219452/Barbecue-Ribs-Recipe-7_ikifom.jpg",
                            MealName = "BBQ Ribs",
                            Price = 14.0,
                            RestaurantId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Vegan bowl with falafel, hummus, and fresh veggies.",
                            MealImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1761219475/Bol_falafels_a18c8367-1a60-4132-8e78-0f8a3f363288_p2ayhu.jpg",
                            MealName = "Falafel Bowl",
                            Price = 7.5,
                            RestaurantId = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "Fresh sea bream with lemon and herbs.",
                            MealImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1761219536/Gegrillte-Dorade-Rezept-ELAG-Grillplatte-Induktionskochfeld-2020-1-2_elvevn.jpg",
                            MealName = "Grilled Sea Bream",
                            Price = 13.0,
                            RestaurantId = 6
                        },
                        new
                        {
                            Id = 7,
                            Description = "Traditional Serbian rolls with meat and rice.",
                            MealImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1761219553/image_vb4wvf.jpg",
                            MealName = "Cabbage Rolls",
                            Price = 6.0,
                            RestaurantId = 7
                        },
                        new
                        {
                            Id = 8,
                            Description = "Thai noodles with peanuts, eggs, and vegetables.",
                            MealImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1761219579/Authentic-Pad-Thai_square-1908_tufobi.jpg",
                            MealName = "Pad Thai",
                            Price = 9.5,
                            RestaurantId = 8
                        },
                        new
                        {
                            Id = 9,
                            Description = "French tart with eggs, cheese, and bacon.",
                            MealImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1761219644/8-quiche-500x500_uvgs6y.webp",
                            MealName = "Quiche Lorraine",
                            Price = 7.0,
                            RestaurantId = 9
                        },
                        new
                        {
                            Id = 10,
                            Description = "Chicken in creamy Indian tomato sauce.",
                            MealImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1761219669/Chicken-Tikka-Masala_0-SQ_cqaxop.jpg",
                            MealName = "Chicken Tikka Masala",
                            Price = 10.5,
                            RestaurantId = 10
                        },
                        new
                        {
                            Id = 11,
                            Description = "Beef burger with cheese, lettuce, and sauce.",
                            MealImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1761219720/frenchs_burger_styled-image_800x800_pqivq6.png",
                            MealName = "Classic Burger",
                            Price = 8.5,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 12,
                            Description = "Traditional soup made from river fish.",
                            MealImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1761219766/fish-soup-in-a-white-bowl-square-e1691445762883_pvfccd.jpg",
                            MealName = "Fish Soup",
                            Price = 5.5,
                            RestaurantId = 6
                        },
                        new
                        {
                            Id = 13,
                            Description = "Pasta with pancetta, eggs, and parmesan.",
                            MealImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1761219822/Spaghetti-carbonara-1-500x500_ummyjp.jpg",
                            MealName = "Pasta Carbonara",
                            Price = 9.0,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 14,
                            Description = "Mixed vegetables stir-fried in soy sauce.",
                            MealImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1761219892/vegetable_stir_fry_hn87jz.jpg",
                            MealName = "Wok Veggies",
                            Price = 7.0,
                            RestaurantId = 8
                        },
                        new
                        {
                            Id = 15,
                            Description = "Premium beef steak with creamy pepper sauce.",
                            MealImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1761219939/Peppercorn-Steak_ae5dkp.jpg",
                            MealName = "Peppercorn Steak",
                            Price = 15.5,
                            RestaurantId = 4
                        },
                        new
                        {
                            Id = 16,
                            Description = "Lasagna with zucchini, eggplant, and tofu.",
                            MealImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1761219985/Vegan-Lasagna-17_sq4o7j.jpg",
                            MealName = "Vegan Lasagna",
                            Price = 8.0,
                            RestaurantId = 5
                        },
                        new
                        {
                            Id = 17,
                            Description = "Grilled tuna fillet with lime and arugula.",
                            MealImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1761220032/close-up-of-grilled-sliced-tuna-steak-medium-rare-1_zpdonx.jpg",
                            MealName = "Tuna Steak",
                            Price = 13.5,
                            RestaurantId = 6
                        },
                        new
                        {
                            Id = 18,
                            Description = "Traditional grilled minced meat served with flatbread and chopped onion.",
                            MealImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1761220073/cevapi-with-onion-on-oval-plater-middle-eastern-cuisine-salad-plates-and-lavash-bread_tlphkv.jpg",
                            MealName = "Ćevapi with Onion",
                            Price = 6.5,
                            RestaurantId = 7
                        },
                        new
                        {
                            Id = 19,
                            Description = "Spicy Thai soup with shrimp, lemongrass, and chili.",
                            MealImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1761220108/Tom-Yum-soup_2_ti1rim.jpg",
                            MealName = "Tom Yum Soup",
                            Price = 7.5,
                            RestaurantId = 8
                        },
                        new
                        {
                            Id = 20,
                            Description = "French toasted sandwich with ham and melted cheese.",
                            MealImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1761220177/croque-monsieur-66a219aa5f0b2.jpg_h29478.jpg",
                            MealName = "Croque Monsieur",
                            Price = 6.0,
                            RestaurantId = 9
                        });
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.NonWorkingDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("NonWorkingDate");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CourierId")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryAddressId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeliveryStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OrderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CourierId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryAddressId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourierId = "c1a2b3d4-e5f6-7890-ab12-cd34ef56gh14",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh01",
                            DeliveryAddressId = 1,
                            RestaurantId = 20,
                            Status = 0,
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 2,
                            CourierId = "c1a2b3d4-e5f6-7890-ab12-cd34ef56gh15",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh02",
                            DeliveryAddressId = 3,
                            OrderTime = new DateTime(2025, 11, 25, 16, 11, 55, 163, DateTimeKind.Utc).AddTicks(4083),
                            RestaurantId = 19,
                            Status = 2,
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 3,
                            CourierId = "c1a2b3d4-e5f6-7890-ab12-cd34ef56gh16",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh03",
                            DeliveryAddressId = 4,
                            RestaurantId = 19,
                            Status = 0,
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 4,
                            CourierId = "c1a2b3d4-e5f6-7890-ab12-cd34ef56gh17",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh04",
                            DeliveryAddressId = 7,
                            RestaurantId = 18,
                            Status = 0,
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 5,
                            CourierId = "c1a2b3d4-e5f6-7890-ab12-cd34ef56gh18",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh05",
                            DeliveryAddressId = 8,
                            RestaurantId = 18,
                            Status = 0,
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 6,
                            CourierId = "c1a2b3d4-e5f6-7890-ab12-cd34ef56gh19",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh06",
                            DeliveryAddressId = 10,
                            RestaurantId = 18,
                            Status = 0,
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 7,
                            CourierId = "c1a2b3d4-e5f6-7890-ab12-cd34ef56gh20",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh07",
                            DeliveryAddressId = 11,
                            RestaurantId = 19,
                            Status = 1,
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 8,
                            CourierId = "c1a2b3d4-e5f6-7890-ab12-cd34ef56gh21",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh08",
                            DeliveryAddressId = 13,
                            RestaurantId = 20,
                            Status = 1,
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 9,
                            CourierId = "c1a2b3d4-e5f6-7890-ab12-cd34ef56gh22",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh09",
                            DeliveryAddressId = 14,
                            RestaurantId = 20,
                            Status = 4,
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 10,
                            CourierId = "c1a2b3d4-e5f6-7890-ab12-cd34ef56gh23",
                            CustomerId = "f1a2b3c4-d5e6-7890-ab12-cd34ef56gh10",
                            DeliveryAddressId = 16,
                            OrderTime = new DateTime(2025, 11, 25, 16, 11, 55, 163, DateTimeKind.Utc).AddTicks(4099),
                            RestaurantId = 20,
                            Status = 4,
                            TotalPrice = 0.0
                        });
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.OrderMeal", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderId", "MealId");

                    b.HasIndex("MealId");

                    b.ToTable("OrderMeal");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RestaurantImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("RestaurantOwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantOwnerId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kralja Petra 12",
                            AverageRating = 6.5,
                            Capacity = 60,
                            City = "Belgrade",
                            Description = "Modern Serbian cuisine with a twist.",
                            Name = "Bistro Nova",
                            RestaurantImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1760980868/1701656104-Le-Petiti-Bistro-Blue-Centar-13_adciqg.jpg",
                            RestaurantOwnerId = "r1a2b3c4-d5e6-7890-ab12-cd34ef56gh24"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Cara Dušana 45",
                            AverageRating = 9.5,
                            Capacity = 80,
                            City = "Novi Sad",
                            Description = "Authentic Italian trattoria.",
                            Name = "La Tavola",
                            RestaurantImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1760981334/caption_e52wiq.jpg",
                            RestaurantOwnerId = "r1a2b3c4-d5e6-7890-ab12-cd34ef56gh24"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Bulevar Oslobođenja 88",
                            AverageRating = 8.1999999999999993,
                            Capacity = 40,
                            City = "Niš",
                            Description = "Japanese sushi bar with minimalist ambiance.",
                            Name = "Sakura Zen",
                            RestaurantImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1760981371/348s_o6zhl9.jpg",
                            RestaurantOwnerId = "r1a2b3c4-d5e6-7890-ab12-cd34ef56gh24"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Trg Slobode 3",
                            AverageRating = 3.7999999999999998,
                            Capacity = 100,
                            City = "Subotica",
                            Description = "American-style BBQ with craft beers.",
                            Name = "Grill & Chill",
                            RestaurantImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1760981740/348s_jvrtl3.jpg",
                            RestaurantOwnerId = "r1a2b3c4-d5e6-7890-ab12-cd34ef56gh24"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Njegoševa 21",
                            AverageRating = 5.0,
                            Capacity = 50,
                            City = "Belgrade",
                            Description = "Vegan restaurant with organic dishes.",
                            Name = "Green Wave",
                            RestaurantImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1760981837/AC9h4noKhAJV-_f5ucmgN7g1uu9vls7RQwFmyblYG2NoZPvK95_Go_jejqToiFswNCJ4-_fS2fTYgpCI5WdS_gfmLhjPLdx3iAPbXUCdeikQHC9o-ZPvLnI8UwM-jWS6mxXZ_bgEMXao_s680-w680-h510-rw_jdbfsp.webp",
                            RestaurantOwnerId = "r1a2b3c4-d5e6-7890-ab12-cd34ef56gh25"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Obala 7",
                            AverageRating = 5.0,
                            Capacity = 90,
                            City = "Herceg Novi",
                            Description = "Mediterranean cuisine with a sea view.",
                            Name = "Casa del Mar",
                            RestaurantImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1760981920/LaDama_10881_20_1_ojaujg.jpg",
                            RestaurantOwnerId = "r1a2b3c4-d5e6-7890-ab12-cd34ef56gh25"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Vojvode Mišića 14",
                            AverageRating = 5.0,
                            Capacity = 70,
                            City = "Kragujevac",
                            Description = "Traditional homemade Serbian food.",
                            Name = "Grandma's Kitchen",
                            RestaurantImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1760981760/im-65599456_e7zznz.jpg",
                            RestaurantOwnerId = "r1a2b3c4-d5e6-7890-ab12-cd34ef56gh26"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Zmaj Jovina 9",
                            AverageRating = 5.0,
                            Capacity = 85,
                            City = "Novi Sad",
                            Description = "Fusion cuisine in a modern setting.",
                            Name = "Urban Spoon",
                            RestaurantImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1760982086/5dc498fe695b58645d6f1dbc_jexb15.png",
                            RestaurantOwnerId = "r1a2b3c4-d5e6-7890-ab12-cd34ef56gh27"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Francuska 5",
                            AverageRating = 8.0,
                            Capacity = 45,
                            City = "Belgrade",
                            Description = "French bistro with croissants and wine.",
                            Name = "Le Petit Café",
                            RestaurantImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1760981871/images_yybf2j.jpg",
                            RestaurantOwnerId = "r1a2b3c4-d5e6-7890-ab12-cd34ef56gh27"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Đure Jakšića 33",
                            AverageRating = 9.0,
                            Capacity = 60,
                            City = "Zrenjanin",
                            Description = "Indian cuisine with authentic spices.",
                            Name = "Tandoori Flame",
                            RestaurantImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1760985797/a-chef-is-cooking-in-his-restaurants-kitchen_gfpjj0.jpg",
                            RestaurantOwnerId = "r1a2b3c4-d5e6-7890-ab12-cd34ef56gh28"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Miletićeva 18",
                            AverageRating = 7.0,
                            Capacity = 55,
                            City = "Pančevo",
                            Description = "Gourmet burgers with homemade sauces.",
                            Name = "Burger Lab",
                            RestaurantImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1760985725/premium_photo-1661883237884-263e8de8869b_fhmc5u.jpg",
                            RestaurantOwnerId = "r1a2b3c4-d5e6-7890-ab12-cd34ef56gh29"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Dunavska 2",
                            AverageRating = 5.0,
                            Capacity = 75,
                            City = "Sombor",
                            Description = "Seafood specialties and river fish.",
                            Name = "Fish Pot",
                            RestaurantImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1760981672/348s_gedljh.jpg",
                            RestaurantOwnerId = "r1a2b3c4-d5e6-7890-ab12-cd34ef56gh30"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Kneza Miloša 27",
                            AverageRating = 5.4000000000000004,
                            Capacity = 65,
                            City = "Belgrade",
                            Description = "Fresh pasta and Italian desserts.",
                            Name = "Pasta Mia",
                            RestaurantImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1760985883/348s_fheyvs.jpg",
                            RestaurantOwnerId = "r1a2b3c4-d5e6-7890-ab12-cd34ef56gh31"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Nikole Pašića 10",
                            AverageRating = 6.7000000000000002,
                            Capacity = 80,
                            City = "Niš",
                            Description = "Asian cuisine with wok and curry dishes.",
                            Name = "Orient Express",
                            RestaurantImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1760985977/348s_pumoab.jpg",
                            RestaurantOwnerId = "r1a2b3c4-d5e6-7890-ab12-cd34ef56gh32"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Bulevar Evrope 21",
                            AverageRating = 8.5999999999999996,
                            Capacity = 95,
                            City = "Novi Sad",
                            Description = "Premium steaks and fine wines.",
                            Name = "Steakhouse 21",
                            RestaurantImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1760986014/ejhsj8xcmjuwdsi8qdmj.jpg",
                            RestaurantOwnerId = "r1a2b3c4-d5e6-7890-ab12-cd34ef56gh33"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Gundulićeva 6",
                            AverageRating = 5.0,
                            Capacity = 70,
                            City = "Belgrade",
                            Description = "Rustic ambiance with local specialties.",
                            Name = "Nest",
                            RestaurantImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1760985649/Most_Beautiful_Restaurants_scotland_December23_PR_Global_pafswr.jpg",
                            RestaurantOwnerId = "r1a2b3c4-d5e6-7890-ab12-cd34ef56gh32"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Petrovaradinska 4",
                            AverageRating = 5.0,
                            Capacity = 60,
                            City = "Novi Sad",
                            Description = "Spanish tapas and sangria.",
                            Name = "Tapas Bar",
                            RestaurantImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1760970771/slikaRestorana1_hibuiy.png",
                            RestaurantOwnerId = "r1a2b3c4-d5e6-7890-ab12-cd34ef56gh28"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Glavna 1",
                            AverageRating = 5.0,
                            Capacity = 100,
                            City = "Valjevo",
                            Description = "Authentic tavern with live folk music.",
                            Name = "Marko's Tavern",
                            RestaurantImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1760985542/07best-restaurants-nashville15-jbkq-videoSixteenByNineJumbo1600_ns15cb.jpg",
                            RestaurantOwnerId = "r1a2b3c4-d5e6-7890-ab12-cd34ef56gh28"
                        },
                        new
                        {
                            Id = 19,
                            Address = "Vojvode Stepe 19",
                            AverageRating = 5.0,
                            Capacity = 50,
                            City = "Belgrade",
                            Description = "Thai cuisine with exotic flavors.",
                            Name = "Thai Orchid",
                            RestaurantImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1760986076/ix3atyp8yzjh6a25r2ms.jpg",
                            RestaurantOwnerId = "r1a2b3c4-d5e6-7890-ab12-cd34ef56gh29"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Skandinavska 3",
                            AverageRating = 5.0,
                            Capacity = 40,
                            City = "Novi Sad",
                            Description = "Nordic cuisine with minimalist design.",
                            Name = "Nordic Table",
                            RestaurantImageUrl = "https://res.cloudinary.com/dsgans7nh/image/upload/v1760986113/Hakkaiza-industrial-restaurant-design2_vyopcv.jpg",
                            RestaurantOwnerId = "r1a2b3c4-d5e6-7890-ab12-cd34ef56gh30"
                        });
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.RestaurantOwner", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RestaurantOwners");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.WorkingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CourierId")
                        .HasColumnType("text");

                    b.Property<int>("DayOfTheWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndingTime")
                        .HasColumnType("interval");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartingTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("CourierId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("WorkingHours");
                });

            modelBuilder.Entity("CustomerAllergens", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Model.Allergen", null)
                        .WithMany()
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gozba_na_klik_backend.Model.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MealAllergens", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Model.Allergen", null)
                        .WithMany()
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gozba_na_klik_backend.Model.Meal", null)
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gozba_na_klik_backend.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Address", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Model.Customer", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Administrator", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Model.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("gozba_na_klik_backend.Model.Administrator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Courier", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Model.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("gozba_na_klik_backend.Model.Courier", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Customer", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Model.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("gozba_na_klik_backend.Model.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Employee", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Model.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("gozba_na_klik_backend.Model.Employee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Extras", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Model.Meal", null)
                        .WithMany("Extras")
                        .HasForeignKey("MealId");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Meal", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Model.Restaurant", null)
                        .WithMany("MealsOnMenu")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.NonWorkingDate", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Model.Restaurant", null)
                        .WithMany("NonWorkingDates")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Order", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Model.Courier", "Courier")
                        .WithMany("Orders")
                        .HasForeignKey("CourierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("gozba_na_klik_backend.Model.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gozba_na_klik_backend.Model.Address", "DeliveryAddress")
                        .WithMany()
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gozba_na_klik_backend.Model.Restaurant", "Restaurant")
                        .WithMany("Orders")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Courier");

                    b.Navigation("Customer");

                    b.Navigation("DeliveryAddress");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.OrderMeal", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Model.Meal", "Meal")
                        .WithMany("OrderMeals")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gozba_na_klik_backend.Model.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Restaurant", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Model.RestaurantOwner", "RestaurantOwner")
                        .WithMany()
                        .HasForeignKey("RestaurantOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RestaurantOwner");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.RestaurantOwner", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Model.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("gozba_na_klik_backend.Model.RestaurantOwner", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.WorkingHours", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Model.Courier", null)
                        .WithMany("WorkingHours")
                        .HasForeignKey("CourierId");

                    b.HasOne("gozba_na_klik_backend.Model.Restaurant", "Restaurant")
                        .WithMany("WorkingHours")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Courier", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Meal", b =>
                {
                    b.Navigation("Extras");

                    b.Navigation("OrderMeals");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Model.Restaurant", b =>
                {
                    b.Navigation("MealsOnMenu");

                    b.Navigation("NonWorkingDates");

                    b.Navigation("Orders");

                    b.Navigation("WorkingHours");
                });
#pragma warning restore 612, 618
        }
    }
}
